# Generated by Django 3.2.4 on 2021-06-30 22:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('name_abbr', models.CharField(max_length=8)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성 시간')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정 시간')),
            ],
            options={
                'db_table': 'artists',
            },
        ),
        migrations.CreateModel(
            name='Party',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('name_abbr', models.CharField(max_length=8)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성 시간')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정 시간')),
            ],
            options={
                'db_table': 'parties',
            },
        ),
        migrations.CreateModel(
            name='ArtistParty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artist', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.artist')),
                ('party', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.party')),
            ],
            options={
                'db_table': 'artists_parties',
            },
        ),
        migrations.AddField(
            model_name='artist',
            name='parties',
            field=models.ManyToManyField(through='api.ArtistParty', to='api.Party'),
        ),
    ]
